export const INDICATIFS = [
  { code: "+33", label: "France" },
  { code: "+32", label: "Belgique" },
  { code: "+41", label: "Suisse" },
  { code: "+49", label: "Allemagne" },
  { code: "+39", label: "Italie" },
  { code: "+34", label: "Espagne" },
  { code: "+44", label: "Royaume-Uni" },
  { code: "+352", label: "Luxembourg" },
  { code: "+31", label: "Pays-Bas" },
  { code: "+351", label: "Portugal" },
  { code: "+46", label: "Suède" },
  { code: "+47", label: "Norvège" },
  { code: "+45", label: "Danemark" },
  { code: "+358", label: "Finlande" },
  { code: "+420", label: "République tchèque" },
  { code: "+48", label: "Pologne" },
  { code: "+36", label: "Hongrie" },
  { code: "+7", label: "Russie" },
  { code: "+380", label: "Ukraine" },
  { code: "+421", label: "Slovaquie" },
  { code: "+386", label: "Slovénie" },
  { code: "+377", label: "Monaco" },
  { code: "+370", label: "Lituanie" },
  { code: "+371", label: "Lettonie" },
  { code: "+372", label: "Estonie" },
  { code: "+423", label: "Liechtenstein" },
  { code: "+356", label: "Malte" },
  { code: "+30", label: "Grèce" },
  { code: "+94", label: "Sri Lanka" },
  { code: "+385", label: "Croatie" },
  { code: "+353", label: "Irlande" },
  { code: "+389", label: "Macédoine" },
  { code: "+381", label: "Serbie" },
  { code: "+382", label: "Monténégro" },
  { code: "+386", label: "Slovénie" },
  { code: "+40", label: "Roumanie" },
  { code: "+423", label: "Liechtenstein" },
  { code: "+357", label: "Chypre" },
  { code: "+995", label: "Géorgie" },
  { code: "+359", label: "Bulgarie" },
  { code: "+1467", label: "Guernesey" },
  { code: "+44", label: "Îles Anglo-Normandes" },
  { code: "+44", label: "Jersey" },
  { code: "+44", label: "Île de Man" },
  { code: "+44", label: "Gibraltar" },
  { code: "+44", label: "Malte" },
];

